language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
cache: pip
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install Cython --install-option="--no-cython-compile"
  - pip install coverage pytest pytest-cov -U
  - pip install lxml pyteomics dill click
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install git+https://github.com/mobiusklein/psims.git
  - pip install git+https://github.com/mobiusklein/python-idzip.git
  - pip install git+https://github.com/mobiusklein/ms_peak_picker.git
  - pip install git+https://github.com/mobiusklein/brainpy.git
  - pip install --upgrade coverage
  - pip install python-idzip >=0.3.2
  - python setup.py develop
  # - pip install -r requirements.txt
# command to run tests
script: make test
