language: python
python:
  - "2.7"
  - "3.5"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
cache: pip
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install cython
  # - pip install git+https://github.com/mobiusklein/brainpy.git
  - pip install lxml pyteomics brain-isotopic-distribution
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install git+https://github.com/mobiusklein/ms_peak_picker.git
  # - pip install -e .
  - python setup.py install
  - pip install --upgrade coverage
  # - pip install -r requirements.txt
# command to run tests
script: nosetests --with-coverage --cover-package=ms_deisotope
